version: '3.7'
services:

## Router
  router01:
    image: mongo:latest
    container_name: router-01
    #Once the Configuration Server has been set up, the Mongos Instance can be started by executing the following command along with the name of your Configuration Server
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - ./scripts:/scripts

## Config Servers
  configsvr01:
    image: mongo:latest
    container_name: mongo-config-01 
    #Starting MongoDB Instance in Configuration Mode
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
    ports:
      - 27119:27017
    links:
      - shard01-a
      - shard02-a 

## Shards
  ## Shards 01
   
  shard01-a:
    image: mongo:latest
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27122:27017
    links:
      - shard01-b
      - shard01-c

## replica shard
  shard01-b:
    image: mongo:latest
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27123:27017

## replica shard
  shard01-c:
    image: mongo:latest
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27124:27017

  ## Shards 02
  shard02-a:
    image: mongo:latest
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27125:27017
    links:
      - shard02-b
      - shard02-c

## replica shard
  shard02-b:
    image: mongo:latest
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27126:27017

## replica shard
  shard02-c:
    image: mongo:latest
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27127:27017